version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:latest"
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - jpa.hibernate.ddl-auto=update
      - jpa.show-sql=true
      - jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

  cours:
    build: ./
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/devops?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - 8082:8082
    image: spring-app
    depends_on:
      - mysqldb
